# Generated by Django 3.0.3 on 2020-02-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0002_pfam_domains_dna'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ccm_models',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='hmm_models',
            name='domain',
        ),
        migrations.AddField(
            model_name='ccm_models',
            name='domain_id',
            field=models.CharField(default=0, max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hmm_models',
            name='domain_id',
            field=models.CharField(default=1, max_length=7),
            preserve_default=False,
        ),
    ]
