# Generated by Django 3.0.3 on 2020-02-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0003_auto_20200219_1308'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ccm_models',
        ),
        migrations.DeleteModel(
            name='hmm_models',
        ),
        migrations.RemoveField(
            model_name='pfam_domains',
            name='dna',
        ),
        migrations.AddField(
            model_name='pfam_domains',
            name='ccm',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='pfam_domains',
            name='hmm',
            field=models.IntegerField(default=32),
        ),
    ]
