from django import forms

class smallannotation_form(forms.Form):
	domains = forms.CharField(widget=forms.Textarea, label="PFAM accession number", initial="PF00875,PF03441,PF03167,PF12546")
	domain_file = forms.FileField(label="Domain File", required=False)
	sequences = forms.CharField(widget=forms.Textarea, label = "Sequences in fasta format", initial=">tr|F0RPZ8|F0RPZ8_DEIPM Uracil-DNA glycosylase OS=Deinococcus proteolyticus (strain ATCC 35074 / DSM 20540 / JCM 6276 / NBRC 101906 / NCIMB 13154 / VKM Ac-1939 / CCM 2703 / MRP) OX=693977 GN=ung PE=3 SV=1\nMQPVAVVWFKKDLRVSDHAALSRAAERGPVLPLYIYEPEQLGHEEFAGHHLTYLNECLHDLSARLARLGAPLVIRYGEAVEVLEALSREVTVGSLWAHQETGNGVSFARDLRVHAWARARGIPFYEPPQQGVIRRMVNRDGWADAWEERMSAPPLPVPALRGVAGTPASLGVLDHAALRVPLGRRVIPQGGEAAAHDILESFLQRRGRDYMWAMSSPLTAEDACSRLSAPLAFGTVSARTVLLATRQALARAVAEQDAQWERSLRSFESRLHWRDHFIQRLESEPRMEFENLNRAYDGLREPHWNEEYFQRWQEGQTGYPLIDATMRMLRATGWLNFRMRAMLVSFAAQHLWLHWRRPGLFLARQWLDNEPGIHWSQMQMQSGTVGINRSRIYSPTRQAREQDPDGEFIRRWVPELAGVPAPHIWRPWELPPLAARGLGLRLGRDYPYPVVDEHAPAREAHRRLQAVRDTPLFAAEARRVYALHGSRKKAVIRAEREKKGLPPRPERPSARRSPLPRRHPMSDQPNLFDTADTQPPVQLPHDWGAVLHDEISRPSFRRLLEFVEEQRRTATVYPPPEDVFTALRLTSYQDAKVLILGQDPYHGAGQAHGLAFSVRRGVRVPPSLRNIYQELKEDVGVTPPRHGNLEAWAERGVLLLNAVLTVREGEPNSHAGQGWEDFTDAVIRALNAKEQRVVFVLWGAYARKKKKLVTAPQHVVIESGHPSPLSVRHFAGTRPFSAVNRALQEAGEEAVDWSLPQ\n>tr|A0A072NB93|A0A072NB93_9DEIO Uracil-DNA glycosylase OS=Deinococcus sp. RL OX=1489678 GN=ung PE=3 SV=1\nMPRPLAGPPVQVVWFKKDLRVADHAPLAAAAERGPVLPLYLYEPEQLGHEEFAGHHLTYLNECLAELDGRLRALGAGLVVRRGEAVAVLEELSELVPMGGLWAHEETGNMVSFQRDRRVRAWARERGVPFAELPQTGVVRRLRDRDGWADLWEERMSAPVVPVPAALRGTDLPPGGLYTHAELGVPANDKTIPPGGESVARATLESFLTVRGVNYLREMSSPLTAEESCSRLSAPLAFGTVSLREVVQATRQRLAAVKGDPDADERWVCSLRSFESRLHWHCHFIQRLESEPQMEVRNLNRAFDGLRPDAGDPGWNADFFDRWAHGQTGYPLVDACMRMLRETGWLNFRMRAMLVSFASQHLWLHWRPTGLFLARQWLDNEPGIHWSQMQMQSSTVGINRVRIYSPTRQAREQDPDGAFIRRWVPELADVPGDFLHAPWEWSGATRLAYPPPVVDEGKAGAAARARIYAARESEAFETEARRVYQKHGSRKKAVLRAERVARGLPAKPVRPPKSAPRRIPPMTDQPGLFGTAPETPKPLIPAGLPDSWREALHDEFAAPYFHALRDFLVEERRQHTVYPPAPDVFNALRYTPLEAVKVLILGQDPYHGPGQAHGLAFSVRPGVRPPPSLANIYKELQADVGFQPPRHGYLRHWAEQGVLLLNAVLTVRRGEPNSHAGRGWERLTDAVIRQVNAKESRVVFVLWGAYARKKAKLVTNPQHVILESAHPSPLSVAKFLGTRPFSKVNAALEESGQTPIDWQLPMEVEE\n>tr|V7B5W0|V7B5W0_PHAVU Photolyase/cryptochrome alpha/beta domain-containing protein OS=Phaseolus vulgaris OX=3885 GN=PHAVU_008G173700g PE=4 SV=1\nMSGGGCSIVWFRRDLRVEDNPALAAGVRAGAVIAVFIWAPEEEGQYYPGRVSRWWLKQSLAHLDSSLRSLGTPLITKRSTNSVSSLLEVIKSTGATQLFFNHLYDPLSLVRDHRTKEVLTAQGITVRSFNSDLLYEPWDVNDAHGQPFTTFSAFWERCLSMPYDPQAPLLPPKRIIPGDASRCPCDTLVFEDELEKASNALLSRAWSPGWSNADKALAAFVNGPLIEYSKNRRKADSATTSFLSPHLHFGEVSVKKVFHLVRIKQVFWANEGNKAGEESVNLFLKSIGLREYSRYISFNHPYSHERPLLGHLKFFPWVVNEGYFKAWRQGRTGYPLVDAGMRELWATGWLHDRIRVVVSSFFVKVLQLPWRWGMKYFWDTLLDADLESDALGWQYISGTLPDGREFDRIDNPQFEGYKCDPNGEYVRRWLPELARLPTEWIHHPWNAPEYVLQAAGIELGSNYPLPIVGIDAAKVRLQEALIQTWQQEAASRAAIENGTEEGLGDSSESAPIAFPQDTLMEERPAEPVRNNPPHGTRRYEDQMVPSMTSSHVRVEEEETSSDLRNSAADNRAEVPTNVTTQQNARETVNQGELLNVNRNTRVQNNATMWLRNAAEDSTAESSISTRRERDGGVVPVWSPPASNFSEQYADDENGIGASSSYLQRQHPQSHQLMNWTRLPQTG")
	fasta_file = forms.FileField(label="Fasta File", required=False)
	dama_choice = forms.BooleanField(label='Do you want to use DAMA?', widget=forms.RadioSelect(choices=[('yes', 'yes'),('no', 'no')]), initial='yes')
	def as_table(self):
		return self._html_output(
			normal_row='<tr%(html_class_attr)s><th>%(label)s</th><td>%(errors)s%(field)s%(help_text)s</td></tr>',
			error_row='<tr><td colspan="2">%s</td></tr>',
			row_ender='</td></tr>',
			help_text_html='<a class="helptext">?<span>%s</span></a>',
			errors_on_separate_row=False)

class largeannotation_form(forms.Form):
	sequences = forms.CharField(widget=forms.Textarea, label = "Sequences in fasta format")
	fasta_file = forms.FileField(label="Fasta File")
	dama_choice = forms.BooleanField(label='Do you want to use DAMA?', widget=forms.RadioSelect(choices=[('yes', 'yes'),('no', 'no')]), initial='yes')
	def as_table(self):
		return self._html_output(
			normal_row='<tr%(html_class_attr)s><th>%(label)s</th><td>%(errors)s%(field)s%(help_text)s</td></tr>',
			error_row='<tr><td colspan="2">%s</td></tr>',
			row_ender='</td></tr>',
			help_text_html='<a class="helptext">?<span>%s</span></a>',
			errors_on_separate_row=False)
